### ISSUE TITLE
Show the status timeline?

### ISSUE THREAD

**Issue by canadaduane** [dariusk/twitter-archiver#4]
Thanks for this project! I just left Twitter and was inspired by this project to archive everything first.

I'm curious if there's a way to show the status timeline--i.e. each tweet from today backwards, up to the point of inauguration of the account?

**Comment by dariusk** [comment]
I'm sure I could do this but what would be the use case here? A paginated view of potentially 100k items seems of limited utility.

**Comment by canadaduane** [comment]
This might sound selfish, but I guess the utility is signaling that I had significant participation in many discussions and/or issues over the years. I want someone who visits my archive to see that I joined Twitter in 2009 and had 40k tweets (or whatever). The paginated view is more of a proof of claim to significance.

I realize that in reality no one cares that much about my tweets haha. But maybe I'm thinking of this archive as a kind of social proof or certificate of authenticity maybe? Like, now that I can't point people to my deleted Twitter account, what can I point them to if they are passingly curious about what I did?


Dec 19, 2022 5:55:49 PM Darius Kazemi ***@***.***>:

**Comment by dariusk** [comment]
I'm considering adding more functionality over time. The nice thing is you
can always rerun the zip if/when I add more features. I guess some kind of
paginated view could be easy enough, even if it's not going to be very
useful.

**Comment by derekeder** [comment]
@dariusk this is a great tool and exactly what i've been looking for. I just published my archive here: https://derekeder.com/twitter/index.html

came here to +1 this feature. showing a paginated view of the most recent tweets would be a good default view as it mimics the behavior of a twitter profile and would give visitors something to see without having to enter any search terms. most people won't know what to search for without seeing some examples of whats in the archive.

**Comment by dariusk** [comment]
@canadaduane @derekeder Okay, I have updated the project to provide a "browse" mode with pagination. When browsing, you can sort by newest first, oldest first, and most popular. You can see it in action here: https://tinysubversions.com/twitter-archive/

And it's deployed to the make-your-own tool page at https://tinysubversions.com/twitter-archive/make-your-own/

Screenshot of what it looks like on an archive: 
![image](https://user-images.githubusercontent.com/266454/210929996-1309605d-63ef-46d4-88f3-879a5cb65d89.png)

**Comment by derekeder** [comment]
@dariusk awesome! I'll try it out!

**Comment by derekeder** [comment]
just got the new version set up. thanks for adding the browse functionality!

I ended up making some customizations to it. I use bootstrap for styles, so incorporated that. Also, combined the browse and search views into one so you see everything by default and when you type in the search box it filters the results. still a few bugs to sort out with the combined interface, but it generally works.

<img width="916" alt="Screen Shot 2023-02-04 at 10 23 31 PM" src="https://user-images.githubusercontent.com/919583/216801470-1c76341e-3700-4286-be09-55c1eda23ff2.png">


demo: https://derekeder.com/twitter/index.html
code: https://github.com/derekeder/derekeder.com/tree/main/twitter
